<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="0" name="WIDM_Test" tests="10" failures="1" timestamp="15 May 2019 19:43:56 GMT" time="263.031" errors="0">
  <testcase name="SetEvironmentLevel" time="0.038" classname="SupportClasses.Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="AAAUserCreate_Email_As_UserId" time="7.099" classname="WIDM_Application.WIDM_SmokeTest"/>
  <testcase name="WIDM_ForgotUserID" time="66.226" classname="WIDM_Application.WIDM_SmokeTest"/>
  <testcase name="WIDM_ResetPassword_Email" time="89.979" classname="WIDM_Application.WIDM_SmokeTest"/>
  <testcase name="WIDM_Login" time="97.889" classname="WIDM_Application.WIDM_SmokeTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at WIDM_Application.WIDM_SmokeTest.WIDM_Login(WIDM_SmokeTest.java:160)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- WIDM_Login -->
  <testcase name="WIDM_RegistrationEFWS" time="183.889" classname="WIDM_Application.WIDM_SmokeTest"/>
  <testcase name="WIDM_Login" time="182.516" classname="WIDM_Application.WIDM_SmokeTest"/>
  <testcase name="WIDM_Registration_ErrorMessages" time="201.386" classname="WIDM_Application.WIDM_SmokeTest"/>
  <testcase name="WIDM_Registration" time="218.435" classname="WIDM_Application.WIDM_SmokeTest"/>
  <testcase name="WIDM_ResetPasswordSecret" time="260.396" classname="WIDM_Application.WIDM_SmokeTest"/>
</testsuite> <!-- WIDM_Test -->
