<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="6" name="Default test" tests="1" failures="1" timestamp="07 May 2019 21:43:36 GMT" time="3.102" errors="0">
  <testcase name="AAAUserCreate" time="2.249" classname="WIDM_Application.WIDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;transactionId&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<transactionId>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at WIDM_Application.WIDM.AAAUserCreate(WIDM.java:108)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AAAUserCreate -->
  <testcase name="WIDM_Registration_ErrorMessages" time="0.0" classname="WIDM_Application.WIDM">
    <ignored/>
  </testcase> <!-- WIDM_Registration_ErrorMessages -->
  <testcase name="WIDM_Registration" time="0.0" classname="WIDM_Application.WIDM">
    <ignored/>
  </testcase> <!-- WIDM_Registration -->
  <testcase name="WIDM_ForgotUserID" time="0.0" classname="WIDM_Application.WIDM">
    <ignored/>
  </testcase> <!-- WIDM_ForgotUserID -->
  <testcase name="WIDM_RegistrationEFWS" time="0.0" classname="WIDM_Application.WIDM">
    <ignored/>
  </testcase> <!-- WIDM_RegistrationEFWS -->
  <testcase name="ResetPasswordWIDM_Email" time="0.0" classname="WIDM_Application.WIDM">
    <ignored/>
  </testcase> <!-- ResetPasswordWIDM_Email -->
  <testcase name="WIDM_ResetPasswordSecret" time="0.0" classname="WIDM_Application.WIDM">
    <ignored/>
  </testcase> <!-- WIDM_ResetPasswordSecret -->
</testsuite> <!-- Default test -->
