<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="1" name="Default test" tests="4" failures="2" timestamp="13 Nov 2018 22:57:59 GMT" time="1397.1" errors="0">
  <testcase name="Account_Number_Masking" time="112.74" classname="WFCL_Application.WFCL_PI_1">
    <failure type="java.lang.AssertionError" message="Request Access from the Account Administrator">
      <![CDATA[java.lang.AssertionError: Request Access from the Account Administrator
at org.testng.Assert.fail(Assert.java:96)
at WFCL_Application.WFCL_PI_1.Account_Number_Masking(WFCL_PI_1.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Account_Number_Masking -->
  <testcase name="Account_Number_Masking" time="128.103" classname="WFCL_Application.WFCL_PI_1">
    <failure type="java.lang.AssertionError" message="Request Access from the Account Administrator">
      <![CDATA[java.lang.AssertionError: Request Access from the Account Administrator
at org.testng.Assert.fail(Assert.java:96)
at WFCL_Application.WFCL_PI_1.Account_Number_Masking(WFCL_PI_1.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Account_Number_Masking -->
  <testcase name="Account_Number_Masking" time="852.131" classname="WFCL_Application.WFCL_PI_1"/>
  <testcase name="Account_Number_Masking" time="852.116" classname="WFCL_Application.WFCL_PI_1"/>
  <testcase name="BR_TaxID" time="0.0" classname="WFCL_Application.WFCL_PI_1">
    <ignored/>
  </testcase> <!-- BR_TaxID -->
</testsuite> <!-- Default test -->
