<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="4" name="WFCL_Test" tests="11" failures="5" timestamp="09 Nov 2018 21:07:22 GMT" time="252.002" errors="0">
  <testcase name="SetEvironmentLevel" time="0.16" classname="SupportClasses.Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="AccountRegistration_WDPA" time="43.011" classname="AgileApplications.WFCL">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at AgileApplications.WFCL.AccountRegistration_WDPA(WFCL.java:222)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- AccountRegistration_WDPA -->
  <testcase name="UserRegistration" time="113.386" classname="AgileApplications.WFCL"/>
  <testcase name="Reset_Password_Email" time="129.99" classname="AgileApplications.WFCL"/>
  <testcase name="Forgot_User_Email" time="162.37" classname="AgileApplications.WFCL"/>
  <testcase name="Password_Reset_Secret" time="173.116" classname="AgileApplications.WFCL"/>
  <testcase name="CreditCardRegistrationEnroll" time="244.554" classname="AgileApplications.WFCL"/>
  <testcase name="AccountRegistration_Linkage" time="2.238" classname="AgileApplications.WFCL">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at AgileApplications.WFCL.AccountRegistration_Linkage(WFCL.java:303)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- AccountRegistration_Linkage -->
  <testcase name="AccountRegistration_INET" time="2.234" classname="AgileApplications.WFCL">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at AgileApplications.WFCL.AccountRegistration_INET(WFCL.java:198)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- AccountRegistration_INET -->
  <testcase name="AccountRegistration_Linkage" time="2.246" classname="AgileApplications.WFCL">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at AgileApplications.WFCL.AccountRegistration_Linkage(WFCL.java:303)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- AccountRegistration_Linkage -->
  <testcase name="AccountRegistration_Admin" time="1.058" classname="AgileApplications.WFCL">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at AgileApplications.WFCL.AccountRegistration_Admin(WFCL.java:183)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- AccountRegistration_Admin -->
  <testcase name="AccountRegistration_GFBO" time="0.0" classname="AgileApplications.WFCL">
    <ignored/>
  </testcase> <!-- AccountRegistration_GFBO -->
  <testcase name="TNT_Vat_Validation" time="0.0" classname="AgileApplications.WFCL">
    <ignored/>
  </testcase> <!-- TNT_Vat_Validation -->
  <testcase name="WADM_Invitaiton" time="0.0" classname="AgileApplications.WFCL">
    <ignored/>
  </testcase> <!-- WADM_Invitaiton -->
  <testcase name="Address_Mismatch" time="0.0" classname="AgileApplications.WFCL">
    <ignored/>
  </testcase> <!-- Address_Mismatch -->
</testsuite> <!-- WFCL_Test -->
