<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="0" name="ADAT_Test" tests="15" failures="8" timestamp="23 Apr 2019 18:39:17 GMT" time="1.553" errors="0">
  <testcase name="SetEvironmentLevel" time="0.044" classname="SupportClasses.Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="ADAT_CreateUser" time="0.404" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_CreateUser" time="0.408" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_CreatePin" time="0.166" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_CreatePin" time="0.198" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_PhoneVelocity" time="0.075" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PhoneVelocity(ADAT.java:114)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_PhoneVelocity -->
  <testcase name="ADAT_AddressVelocity" time="0.089" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_AddressVelocity(ADAT.java:96)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_AddressVelocity -->
  <testcase name="ADAT_PostcardVelocity" time="0.15" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PostcardVelocity(ADAT.java:105)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_PostcardVelocity -->
  <testcase name="ADAT_PhoneVelocity" time="0.157" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PhoneVelocity(ADAT.java:114)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_PhoneVelocity -->
  <testcase name="ADAT_AddressVelocity" time="0.172" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_AddressVelocity(ADAT.java:96)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_AddressVelocity -->
  <testcase name="ADAT_PostcardVelocity" time="0.157" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PostcardVelocity(ADAT.java:105)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_PostcardVelocity -->
  <testcase name="ADAT_VerifyPin_Invalid" time="0.209" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;400Bad&amp;quot;
     but: was &amp;quot;&amp;lt;?xml version=&amp;quot;1.0&amp;quot; encoding=&amp;quot;UTF-8&amp;quot;?&amp;gt;
&amp;lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&amp;quot;http://www.w3.org/2003/05/soap-envelope&amp;quot; xmlns:SOAP-ENC=&amp;quot;http://www.w3.org/2003/05/soap-encoding&amp;quot; xmlns:xsi=&amp;quot;http://www.w3.org/2001/XMLSchema-instance&amp;quot; xmlns:xsd=&amp;quot;http://www.w3.org/2001/XMLSchema&amp;quot; xmlns:cx=&amp;quot;http://ws.arcot.com/WebFortCommonAPI/7.0/xsd&amp;quot; xmlns:wfiss60msgs=&amp;quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/msgs&amp;quot; xmlns:wfiss60xsd=&amp;quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/xsd&amp;quot; xmlns:wfiss60soap11=&amp;quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP11Binding&amp;quot; xmlns:wfiss60soap12=&amp;quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP12Binding&amp;quot; xmlns:wfauth60msgs=&amp;quot;http://ws.arcot.com/WebFortAuthAPI/7.0/msgs&amp;quot; xmlns:wfauth60xsd=&amp;quot;http://ws.arcot.com/WebFortAuthAPI/7.0/xsd&amp;quot; xmlns:wfauth60soap11=&amp;quot;http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP11Binding&amp;quot; xmlns:wfauth60soap12=&amp;quot;http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP12Binding&amp;quot; xmlns:wfauth50soap11=&amp;quot;http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP11Binding&amp;quot; xmlns:wfauth50types=&amp;quot;http://schemas.arcot.com/webfort/v1/types&amp;quot; xmlns:wfauth50soap12=&amp;quot;http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP12Binding&amp;quot; xmlns:wfautha541soap11=&amp;quot;http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP11Binding&amp;quot; xmlns:wfautha541soap12=&amp;quot;http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP12Binding&amp;quot; xmlns:wfauthx541soap11=&amp;quot;http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP11Binding&amp;quot; xmlns:wfauth541types=&amp;quot;http://schemas.arcot.com/webfort/v2/types&amp;quot; xmlns:wfauthx541soap12=&amp;quot;http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP12Binding&amp;quot; xmlns:wfiss50soap11=&amp;quot;http://schemas.arcot.com/regfort/v1/RegFortAPISOAP11Binding&amp;quot; xmlns:wfiss50types=&amp;quot;http://schemas.arcot.com/regfort/v1/types&amp;quot; xmlns:wfiss50soap12=&amp;quot;http://schemas.arcot.com/regfort/v1/RegFortAPISOAP12Binding&amp;quot; xmlns:wfiss541soap11=&amp;quot;http://schemas.arcot.com/regfort/v2/RegFortAPISOAP11Binding&amp;quot; xmlns:wfiss541types=&amp;quot;http://schemas.arcot.com/regfort/v2/types&amp;quot; xmlns:wfiss541soap12=&amp;quot;http://schemas.arcot.com/regfort/v2/RegFortAPISOAP12Binding&amp;quot;&amp;gt;&amp;lt;SOAP-ENV:Header&amp;gt;&amp;lt;/SOAP-ENV:Header&amp;gt;&amp;lt;SOAP-ENV:Body&amp;gt;&amp;lt;SOAP-ENV:Fault&amp;gt;&amp;lt;SOAP-ENV:Code&amp;gt;&amp;lt;SOAP-ENV:Value&amp;gt;SOAP-ENV:Sender&amp;lt;/SOAP-ENV:Value&amp;gt;&amp;lt;/SOAP-ENV:Code&amp;gt;&amp;lt;SOAP-ENV:Reason&amp;gt;&amp;lt;SOAP-ENV:Text xml:lang=&amp;quot;en&amp;quot;&amp;gt;WebFortAuthFault&amp;lt;/SOAP-ENV:Text&amp;gt;&amp;lt;/SOAP-ENV:Reason&amp;gt;&amp;lt;SOAP-ENV:Detail&amp;gt;&amp;lt;wfauth60msgs:WebFortAuthFault&amp;gt;&amp;lt;cx:message&amp;gt;The provided authentication credentials are not correct.&amp;lt;/cx:message&amp;gt;&amp;lt;cx:reasonCode&amp;gt;0&amp;lt;/cx:reasonCode&amp;gt;&amp;lt;cx:responseCode&amp;gt;5707&amp;lt;/cx:responseCode&amp;gt;&amp;lt;cx:transactionID&amp;gt;37358032&amp;lt;/cx:transactionID&amp;gt;&amp;lt;cx:additionalOutput&amp;gt;&amp;lt;/cx:additionalOutput&amp;gt;&amp;lt;wfauth60msgs:credType&amp;gt;4&amp;lt;/wfauth60msgs:credType&amp;gt;&amp;lt;/wfauth60msgs:WebFortAuthFault&amp;gt;&amp;lt;/SOAP-ENV:Detail&amp;gt;&amp;lt;/SOAP-ENV:Fault&amp;gt;&amp;lt;/SOAP-ENV:Body&amp;gt;&amp;lt;/SOAP-ENV:Envelope&amp;gt;
&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "400Bad"
     but: was "<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cx="http://ws.arcot.com/WebFortCommonAPI/7.0/xsd" xmlns:wfiss60msgs="http://ws.arcot.com/WebFortIssuanceAPI/6.0/msgs" xmlns:wfiss60xsd="http://ws.arcot.com/WebFortIssuanceAPI/6.0/xsd" xmlns:wfiss60soap11="http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP11Binding" xmlns:wfiss60soap12="http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP12Binding" xmlns:wfauth60msgs="http://ws.arcot.com/WebFortAuthAPI/7.0/msgs" xmlns:wfauth60xsd="http://ws.arcot.com/WebFortAuthAPI/7.0/xsd" xmlns:wfauth60soap11="http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP11Binding" xmlns:wfauth60soap12="http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP12Binding" xmlns:wfauth50soap11="http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP11Binding" xmlns:wfauth50types="http://schemas.arcot.com/webfort/v1/types" xmlns:wfauth50soap12="http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP12Binding" xmlns:wfautha541soap11="http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP11Binding" xmlns:wfautha541soap12="http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP12Binding" xmlns:wfauthx541soap11="http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP11Binding" xmlns:wfauth541types="http://schemas.arcot.com/webfort/v2/types" xmlns:wfauthx541soap12="http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP12Binding" xmlns:wfiss50soap11="http://schemas.arcot.com/regfort/v1/RegFortAPISOAP11Binding" xmlns:wfiss50types="http://schemas.arcot.com/regfort/v1/types" xmlns:wfiss50soap12="http://schemas.arcot.com/regfort/v1/RegFortAPISOAP12Binding" xmlns:wfiss541soap11="http://schemas.arcot.com/regfort/v2/RegFortAPISOAP11Binding" xmlns:wfiss541types="http://schemas.arcot.com/regfort/v2/types" xmlns:wfiss541soap12="http://schemas.arcot.com/regfort/v2/RegFortAPISOAP12Binding"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">WebFortAuthFault</SOAP-ENV:Text></SOAP-ENV:Reason><SOAP-ENV:Detail><wfauth60msgs:WebFortAuthFault><cx:message>The provided authentication credentials are not correct.</cx:message><cx:reasonCode>0</cx:reasonCode><cx:responseCode>5707</cx:responseCode><cx:transactionID>37358032</cx:transactionID><cx:additionalOutput></cx:additionalOutput><wfauth60msgs:credType>4</wfauth60msgs:credType></wfauth60msgs:WebFortAuthFault></SOAP-ENV:Detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_VerifyPin_Invalid(ADAT.java:149)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_VerifyPin_Invalid -->
  <testcase name="ADAT_VerifyPin_Invalid" time="0.214" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;400Bad&amp;quot;
     but: was &amp;quot;&amp;lt;?xml version=&amp;quot;1.0&amp;quot; encoding=&amp;quot;UTF-8&amp;quot;?&amp;gt;
&amp;lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&amp;quot;http://www.w3.org/2003/05/soap-envelope&amp;quot; xmlns:SOAP-ENC=&amp;quot;http://www.w3.org/2003/05/soap-encoding&amp;quot; xmlns:xsi=&amp;quot;http://www.w3.org/2001/XMLSchema-instance&amp;quot; xmlns:xsd=&amp;quot;http://www.w3.org/2001/XMLSchema&amp;quot; xmlns:cx=&amp;quot;http://ws.arcot.com/WebFortCommonAPI/7.0/xsd&amp;quot; xmlns:wfiss60msgs=&amp;quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/msgs&amp;quot; xmlns:wfiss60xsd=&amp;quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/xsd&amp;quot; xmlns:wfiss60soap11=&amp;quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP11Binding&amp;quot; xmlns:wfiss60soap12=&amp;quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP12Binding&amp;quot; xmlns:wfauth60msgs=&amp;quot;http://ws.arcot.com/WebFortAuthAPI/7.0/msgs&amp;quot; xmlns:wfauth60xsd=&amp;quot;http://ws.arcot.com/WebFortAuthAPI/7.0/xsd&amp;quot; xmlns:wfauth60soap11=&amp;quot;http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP11Binding&amp;quot; xmlns:wfauth60soap12=&amp;quot;http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP12Binding&amp;quot; xmlns:wfauth50soap11=&amp;quot;http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP11Binding&amp;quot; xmlns:wfauth50types=&amp;quot;http://schemas.arcot.com/webfort/v1/types&amp;quot; xmlns:wfauth50soap12=&amp;quot;http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP12Binding&amp;quot; xmlns:wfautha541soap11=&amp;quot;http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP11Binding&amp;quot; xmlns:wfautha541soap12=&amp;quot;http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP12Binding&amp;quot; xmlns:wfauthx541soap11=&amp;quot;http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP11Binding&amp;quot; xmlns:wfauth541types=&amp;quot;http://schemas.arcot.com/webfort/v2/types&amp;quot; xmlns:wfauthx541soap12=&amp;quot;http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP12Binding&amp;quot; xmlns:wfiss50soap11=&amp;quot;http://schemas.arcot.com/regfort/v1/RegFortAPISOAP11Binding&amp;quot; xmlns:wfiss50types=&amp;quot;http://schemas.arcot.com/regfort/v1/types&amp;quot; xmlns:wfiss50soap12=&amp;quot;http://schemas.arcot.com/regfort/v1/RegFortAPISOAP12Binding&amp;quot; xmlns:wfiss541soap11=&amp;quot;http://schemas.arcot.com/regfort/v2/RegFortAPISOAP11Binding&amp;quot; xmlns:wfiss541types=&amp;quot;http://schemas.arcot.com/regfort/v2/types&amp;quot; xmlns:wfiss541soap12=&amp;quot;http://schemas.arcot.com/regfort/v2/RegFortAPISOAP12Binding&amp;quot;&amp;gt;&amp;lt;SOAP-ENV:Header&amp;gt;&amp;lt;/SOAP-ENV:Header&amp;gt;&amp;lt;SOAP-ENV:Body&amp;gt;&amp;lt;SOAP-ENV:Fault&amp;gt;&amp;lt;SOAP-ENV:Code&amp;gt;&amp;lt;SOAP-ENV:Value&amp;gt;SOAP-ENV:Sender&amp;lt;/SOAP-ENV:Value&amp;gt;&amp;lt;/SOAP-ENV:Code&amp;gt;&amp;lt;SOAP-ENV:Reason&amp;gt;&amp;lt;SOAP-ENV:Text xml:lang=&amp;quot;en&amp;quot;&amp;gt;WebFortAuthFault&amp;lt;/SOAP-ENV:Text&amp;gt;&amp;lt;/SOAP-ENV:Reason&amp;gt;&amp;lt;SOAP-ENV:Detail&amp;gt;&amp;lt;wfauth60msgs:WebFortAuthFault&amp;gt;&amp;lt;cx:message&amp;gt;The provided authentication credentials are not correct.&amp;lt;/cx:message&amp;gt;&amp;lt;cx:reasonCode&amp;gt;0&amp;lt;/cx:reasonCode&amp;gt;&amp;lt;cx:responseCode&amp;gt;5707&amp;lt;/cx:responseCode&amp;gt;&amp;lt;cx:transactionID&amp;gt;37358031&amp;lt;/cx:transactionID&amp;gt;&amp;lt;cx:additionalOutput&amp;gt;&amp;lt;/cx:additionalOutput&amp;gt;&amp;lt;wfauth60msgs:credType&amp;gt;4&amp;lt;/wfauth60msgs:credType&amp;gt;&amp;lt;/wfauth60msgs:WebFortAuthFault&amp;gt;&amp;lt;/SOAP-ENV:Detail&amp;gt;&amp;lt;/SOAP-ENV:Fault&amp;gt;&amp;lt;/SOAP-ENV:Body&amp;gt;&amp;lt;/SOAP-ENV:Envelope&amp;gt;
&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "400Bad"
     but: was "<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cx="http://ws.arcot.com/WebFortCommonAPI/7.0/xsd" xmlns:wfiss60msgs="http://ws.arcot.com/WebFortIssuanceAPI/6.0/msgs" xmlns:wfiss60xsd="http://ws.arcot.com/WebFortIssuanceAPI/6.0/xsd" xmlns:wfiss60soap11="http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP11Binding" xmlns:wfiss60soap12="http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP12Binding" xmlns:wfauth60msgs="http://ws.arcot.com/WebFortAuthAPI/7.0/msgs" xmlns:wfauth60xsd="http://ws.arcot.com/WebFortAuthAPI/7.0/xsd" xmlns:wfauth60soap11="http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP11Binding" xmlns:wfauth60soap12="http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP12Binding" xmlns:wfauth50soap11="http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP11Binding" xmlns:wfauth50types="http://schemas.arcot.com/webfort/v1/types" xmlns:wfauth50soap12="http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP12Binding" xmlns:wfautha541soap11="http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP11Binding" xmlns:wfautha541soap12="http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP12Binding" xmlns:wfauthx541soap11="http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP11Binding" xmlns:wfauth541types="http://schemas.arcot.com/webfort/v2/types" xmlns:wfauthx541soap12="http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP12Binding" xmlns:wfiss50soap11="http://schemas.arcot.com/regfort/v1/RegFortAPISOAP11Binding" xmlns:wfiss50types="http://schemas.arcot.com/regfort/v1/types" xmlns:wfiss50soap12="http://schemas.arcot.com/regfort/v1/RegFortAPISOAP12Binding" xmlns:wfiss541soap11="http://schemas.arcot.com/regfort/v2/RegFortAPISOAP11Binding" xmlns:wfiss541types="http://schemas.arcot.com/regfort/v2/types" xmlns:wfiss541soap12="http://schemas.arcot.com/regfort/v2/RegFortAPISOAP12Binding"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">WebFortAuthFault</SOAP-ENV:Text></SOAP-ENV:Reason><SOAP-ENV:Detail><wfauth60msgs:WebFortAuthFault><cx:message>The provided authentication credentials are not correct.</cx:message><cx:reasonCode>0</cx:reasonCode><cx:responseCode>5707</cx:responseCode><cx:transactionID>37358031</cx:transactionID><cx:additionalOutput></cx:additionalOutput><wfauth60msgs:credType>4</wfauth60msgs:credType></wfauth60msgs:WebFortAuthFault></SOAP-ENV:Detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_VerifyPin_Invalid(ADAT.java:149)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_VerifyPin_Invalid -->
  <testcase name="ADAT_VerifyPin" time="0.264" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_VerifyPin" time="0.301" classname="ADAT_Application.ADAT"/>
</testsuite> <!-- ADAT_Test -->
