<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="Mission_Critical.PI2SystemDemo" tests="20" failures="3" timestamp="29 Jan 2019 17:03:13 GMT" time="2757.511" errors="0">
  <testcase name="WIDM_Registration_Email_Validation" time="166.086" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WIDM_Registration_Email_Validation" time="250.686" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WIDM_Registration_Email_Validation" time="316.297" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WIDM_Registration_Email_Validation" time="317.692" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WIDM_Registration_Email_Validation" time="319.681" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WIDM_Registration_Email_Validation" time="249.216" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Registration_Email_Validation" time="105.147" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Registration_Email_Validation" time="105.921" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Registration_Email_Validation" time="104.336" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Registration_Email_Validation" time="41.712" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Registration_Email_Validation" time="40.957" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Registration_Email_Validation" time="42.437" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Registration_Email_Validation_Legacy" time="12.955" classname="Mission_Critical.PI2SystemDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at Mission_Critical.PI2SystemDemo.WFCL_Registration_Email_Validation_Legacy(PI2SystemDemo.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- WFCL_Registration_Email_Validation_Legacy -->
  <testcase name="WFCL_Registration_Email_Validation_Legacy" time="57.461" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Registration_Email_Validation_Legacy" time="77.465" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Registration_Email_Validation_Legacy" time="13.563" classname="Mission_Critical.PI2SystemDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at Mission_Critical.PI2SystemDemo.WFCL_Registration_Email_Validation_Legacy(PI2SystemDemo.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- WFCL_Registration_Email_Validation_Legacy -->
  <testcase name="WFCL_Registration_Email_Validation_Legacy" time="27.860" classname="Mission_Critical.PI2SystemDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at Mission_Critical.PI2SystemDemo.WFCL_Registration_Email_Validation_Legacy(PI2SystemDemo.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- WFCL_Registration_Email_Validation_Legacy -->
  <testcase name="WFCL_Registration_Email_Validation_Legacy" time="76.479" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WIDM_Reset_Password_Secret_SamePassword_Error" time="267.811" classname="Mission_Critical.PI2SystemDemo"/>
  <testcase name="WFCL_Reset_Password_Secret_SamePassword_Error" time="163.749" classname="Mission_Critical.PI2SystemDemo"/>
</testsuite> <!-- Mission_Critical.PI2SystemDemo -->
