<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="WTC-5159473-l2" name="WDPA_Application.WDPA" tests="2" failures="1" timestamp="09 May 2019 18:52:29 GMT" time="83.487" errors="0">
  <testcase name="Pickup_Express" time="83.487" classname="WDPA_Application.WDPA">
    <failure type="java.lang.AssertionError" message="Please correct the error(s) in red.">
      <![CDATA[java.lang.AssertionError: Please correct the error(s) in red.
at org.testng.Assert.fail(Assert.java:96)
at WDPA_Application.WDPA.Pickup_Express(WDPA.java:131)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Pickup_Express -->
  <testcase name="Looping_LTL" classname="WDPA_Application.WDPA">
    <skipped/>
  </testcase> <!-- Looping_LTL -->
</testsuite> <!-- WDPA_Application.WDPA -->
